services:
  - type: web
    plan: free
    name: celery-worker
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A website.make_celery worker --loglevel DEBUG"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.9.18"
  - type: web
    plan: free
    name: app
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: DATABASE_URL
        sync: false
      - key: ENDPOINT_ID
        value: "2258816896893714432"
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: "/etc/secrets/service-acct-google.json"
      - key: PROJECT_ID
        value: "574846571370"
      - key: PYTHON_VERSION
        value: "3.9.18"
  - type: web
    plan: free
    name: flower
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery flower --app tasks --loglevel info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.9.18"
  - type: redis
    plan: free
    name: celery-redis
    region: ohio
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
