"""adding MISSED column to GoalProgress model

Revision ID: f043752c4f79
Revises: 9296551de896
Create Date: 2024-03-27 10:41:59.846264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f043752c4f79'
down_revision = '9296551de896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_progresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('missed', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_progresses', schema=None) as batch_op:
        batch_op.drop_column('missed')

    # ### end Alembic commands ###
